---

- name: Start Redis container
  containers.podman.podman_container:
    name: "{{ redis_container_name }}"
    image: docker.io/redis:latest
    state: started
    restart_policy: always
    recreate: true
    # publish:
    #   - "6379:6379"
    network: "{{ podman_network_name }}"
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
  register: _container_start_results
# - debug: var=_container_start_results

- name: Enable systemd service
  ansible.builtin.service:
    name: "{{ (_container_start_results.podman_systemd | dict2items | list | first).key }}"
    enabled: true
