---
- name: Include podman_init_vars.yml from sleif.podman
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: sleif.podman/tasks/includes/podman_init_vars.yml
      paths: "{{ lookup('config', 'DEFAULT_ROLES_PATH') }}"

- name: Include role sleif.podman podman_operation pod_create
  ansible.builtin.include_role:
    name: sleif.podman
    apply:
      tags:
        - podman_pod_create
  vars:
    podman_operation: pod_create
  tags: always

- name: Create Redis container
  become: "{{ podman_rootless | d(true) | bool }}"
  become_user: "{{ podman_user if podman_rootless | d(true) | bool else omit }}"
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: docker.io/redis:latest
    state: created
    pod: "{{ pod_name | default(omit) }}"
    restart_policy: always
    recreate: "{{ podman_container_recreate | d(false) }}"
    # publish:
    #   - "6379:6379"
    network: "{{ podman_network_name }}"
    timezone: "local"
  register: _container_create_results

# - debug: var=_container_create_results

- name: Include role sleif.podman podman_operation podman_generate_systemd
  ansible.builtin.include_role:
    name: sleif.podman
    apply:
      tags:
        - podman_generate_systemd
  vars:
    podman_operation: podman_generate_systemd
    target: "{{ pod_name if pod_name is defined and pod_name | length > 0 else container_name }}"
  tags: always
