---
- name: Include podman_init_vars.yml from sleif.podman
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: sleif.podman/tasks/includes/podman_init_vars.yml
      paths: "{{ lookup('config', 'DEFAULT_ROLES_PATH') }}"

- name: include_role sleif.podman podman_operation podman_create_container for redis
  ansible.builtin.include_role:
    name: sleif.podman
    apply:
      tags:
        - podman_container_create
  vars:
    # podman_rootless: true
    # podman_network_name: "{{ podman_networks.podman_network_rootless.podman_network_name if podman_rootless | bool else
    #   podman_networks.podman_network_root.podman_network_name }}"
    podman_operation: podman_container_create
    container_name: '{{ redis_container_name }}'
    target: "{{ pod_name if pod_name | d('') is truthy else redis_container_name }}"
    _container:
      name: '{{ container_name }}'
      image:
        name: "{{ redis_container_image }}"
        tag: "{{ redis_container_image_tag }}"
      network: "{{ podman_network_name if pod_name | d('') is falsy else [] }}"
      pod: "{{ pod_name | default(omit) }}"
      # publish: '{{ container_published_ports | default(["6379:6379"]) }}'
      timezone: "Europe/Berlin"
  tags: podman_container_create
